from pydantic import BaseModel

class ColumnConfig(BaseModel):
    """Configuração de anonimização para uma base de dados"""
    name: str
    hash_columns: list[str]
    drop_columns: list[str]
    generalize_columns: dict[str, str] = {}
    enrich_conversao_curada: bool = False


ANONYMIZATION_CONFIGS: list[ColumnConfig] = [
    ColumnConfig(
        name="atendimento_emergencia",
        hash_columns=[
            "PRESTADOR",
            "USUARIO_CLASSIF",
            "USUARIO_CAD_RECEPCAO",
            "USUARIO_ALTA",
        ],
        drop_columns=[
            "NM_PACIENTE",
            "CEP",
            "ENDERECO",
            "BAIRRO",
            "CIDADE",
            "UF",
        ],
        generalize_columns={
            "DT_NASC": "age_only",
        },
        enrich_conversao_curada=True,
    ),
    ColumnConfig(
        name="internacoes",
        hash_columns=[
            "CD_PRESTADOR",
            "PRESTADOR",
        ],
        drop_columns=[
            "PACIENTE",
        ],
        generalize_columns={},
    ),
    ColumnConfig(
        name="movimentacoes",
        hash_columns=[
            "Paciente",
        ],
        drop_columns=[
            "Nome Social",
        ],
        generalize_columns={},
    ),
    ColumnConfig(
        name="cirurgias",
        hash_columns=[
            "CD_AVISO_CIRURGIA",
            "CIRURGIAO_01",
            "CIRURGIAO_02",
            "ASSISTENTE_01",
            "ASSISTENTE_02",
            "ANESTESISTA_01",
            "ANESTESISTA_02",
            "CRM",
            "CRM_01",
            "CRM_02",
            "USUARIO_CONFIRMA_CIRURGIA",
        ],
        drop_columns=[
            "NOME_PACIENTE",
            "DATA_NASCIMENTO",
        ],
        generalize_columns={},
    ),
    ColumnConfig(
        name="exames_imagem",
        hash_columns=[
            "MEDICO_EXECUTANTE",
            "MEDICO_LAUDO_DEFINITIVO",
            "MEDICO_LAUDO_DITADO",
            "MEDICO_LAUDO_PRELIMINAR",
            "MEDICO_LAUDO_ULTIMAMODIFICACAO",
            "MEDICO_LAUDO_WETREAD",
            "MEDICO_SOLICITANTE",
            "DIGITADOR_LAUDO_TRANSCRITO",
        ],
        drop_columns=[
            "NOME_PACIENTE",
            "PATIENT_PERSON_KEY",
        ],
        generalize_columns={},
    ),
    ColumnConfig(
        name="atendimentos_box",
        hash_columns=[
        ],
        drop_columns=[
            "NM_PACIENTE",
        ],
        generalize_columns={},
    ),
    ColumnConfig(
        name="altas",
        hash_columns=[
            "PREST_ADMISSAO",
            "PRESC_MED",
            "PREST_ALTA",
            "USUARIO_ALTA_MEDICA",
            "NM_USUARIO_ALTA_HOSPITALAR",
        ],
        drop_columns=[
            "PACIENTE",
        ],
        generalize_columns={},
    ),
    ColumnConfig(
        name="epidemio",
        hash_columns=[
            "crm_prestador",
            "medico_sumario_alta",
            "cod_conselho",
            "ds_codigo_conselho",
            "medico_resp_atend",
            "liberacao_alta",
            "resp_alta",
            "nm_med_presc",
            "prestador1",
            "prestador2",
        ],
        drop_columns=[
            "nome_paciente",
            "nr_cpf",
            "data_nascimento",
            "cep",
            "endereco",
            "bairro",
            "municipio",
            "uf",
        ],
        generalize_columns={},
    ),
    ColumnConfig(
        name="exames_laboratoriais_limpo",
        hash_columns=[
        ],
        drop_columns=[
            "NM_PACIENTE",
        ],
        generalize_columns={},
    ),
    ColumnConfig(
        name="movimentacoes_limpo",
        hash_columns=[
        ],
        drop_columns=[
            "NM_PACIENTE"
        ],
        generalize_columns={},
    ),
]